version: "2"

services: 
  db: 
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题
    ports:
      - "3306:3306"
    volumes: 
      - /opt/mysql:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: P@ssW0rd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: qwert
      MYSQL_PASSWORD: asdfg
  wordpress: 
    depends_on: 
      - db
    image: wordpress:latest
    ports: 
      - "8888:80"
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: qwert
      WORDPRESS_DB_PASSWORD: asdfg
volumes: 
  db_data: 
